name: Playwright Tests

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      aktifkan_random_delay:
        description: 'Centang untuk aktifkan Random Delay (Default: ON)'
        type: boolean
        required: false
        default: true
      paksa_simpan_video:
        description: 'Centang jika ingin paksa rekam video untuk ditonton (Default: OFF)'
        type: boolean
        required: false
        default: false

jobs:
  test:
    timeout-minutes: 29
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MAX_FUEL_PRICE: ${{ vars.MAX_FUEL_PRICE }}
          MAX_CO2_PRICE: ${{ vars.MAX_CO2_PRICE }}
          REPAIR_WEAR: ${{ vars.REPAIR_WEAR }}
          HOURS_CHECK: ${{ vars.HOURS_CHECK }}
          INCREASE_AIRLINE_REPUTATION: ${{ vars.INCREASE_AIRLINE_REPUTATION }}
          INPUT_RANDOM_DELAY: ${{ github.event.inputs.aktifkan_random_delay }}
          INPUT_RECORD_VIDEO: ${{ github.event.inputs.paksa_simpan_video }}
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
